name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        script:
          - blazor-wasm-aot
          - blazor-wasm-aot2
          - blazor-wasm
          - functions-dotnet6-inproc
          - functions-dotnet6-isolated
          - functions-dotnetcore3.1-inproc
          - functions-node12
          - functions-python3.8
    steps:
      - uses: actions/checkout@v2
      - name: ${{ matrix.script }}
        run: |
          chmod +x *
          docker run --rm -v $(pwd):/scripts oryxtestacr.azurecr.io/public/oryx/build:azfunc-jamstack-test /scripts/${{ matrix.script }}.sh
